version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:  
    jobs:
      - deploy-infrastructure

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/server.yml \
              --tags project="wpp" \
              --stack-name "backend-wpp" \